services:
  - type: web
    name: artebot
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
